"""Provider-neutral port protocols, boundary models, and stable port failures."""

from .adaptation import PatchWorkspace, ValidationRunner
from .artifacts import ArtifactStore, DatasetCatalog
from .base import AsyncBinaryReader
from .common import (
    ArtifactDescriptor,
    AuditEvent,
    CancellationResult,
    DatasetMountSpec,
    DownloadGrant,
    ExternalPaperId,
    ExternalRunStatus,
    FrozenRunSpec,
    GenerationUsage,
    MetricPoint,
    OperationContext,
    PaperQuery,
    PaperSearchPage,
    PatchDocument,
    PatchResult,
    PortModel,
    RawPaperRecord,
    RepositoryAnalysis,
    RepositoryFileSummary,
    RepositoryMetadata,
    RepositoryPolicy,
    RepositoryResolution,
    RunManifest,
    StructuredGenerationRequest,
    StructuredGenerationResult,
    SubmissionResult,
    TrackerRunRef,
    ValidationStageSpec,
    WorkspaceRef,
)
from .errors import (
    ArtifactError,
    CapabilityNotSupportedError,
    ExecutorError,
    FakeScriptExhaustedError,
    IdempotencyConflictError,
    IdempotencyKeyRequiredError,
    LLMError,
    OperationCancelledError,
    OperationTimeoutError,
    PersistenceError,
    PortError,
    ProviderError,
    StructuredOutputValidationError,
    TrackerError,
    make_failure,
)
from .execution import ExperimentExecutor
from .llm import StructuredLLM
from .papers import PaperProvider
from .persistence import (
    AdaptationRepository,
    ApprovalRepository,
    AuditRepository,
    EntityRepository,
    ExperimentRepository,
    OperationRepository,
    PaperRepository,
    RepositorySnapshotRepository,
    ResearchRequestRepository,
    UnitOfWork,
)
from .repositories import RepositoryProvider, StaticRepositoryAnalyzer
from .tracking import ExperimentTracker

__all__ = [
    "AdaptationRepository",
    "ApprovalRepository",
    "ArtifactDescriptor",
    "ArtifactError",
    "ArtifactStore",
    "AsyncBinaryReader",
    "AuditEvent",
    "AuditRepository",
    "CancellationResult",
    "CapabilityNotSupportedError",
    "DatasetCatalog",
    "DatasetMountSpec",
    "DownloadGrant",
    "EntityRepository",
    "ExecutorError",
    "ExperimentExecutor",
    "ExperimentRepository",
    "ExperimentTracker",
    "ExternalPaperId",
    "ExternalRunStatus",
    "FakeScriptExhaustedError",
    "FrozenRunSpec",
    "GenerationUsage",
    "IdempotencyConflictError",
    "IdempotencyKeyRequiredError",
    "LLMError",
    "MetricPoint",
    "OperationCancelledError",
    "OperationContext",
    "OperationRepository",
    "OperationTimeoutError",
    "PaperProvider",
    "PaperQuery",
    "PaperRepository",
    "PaperSearchPage",
    "PatchDocument",
    "PatchResult",
    "PatchWorkspace",
    "PersistenceError",
    "PortError",
    "PortModel",
    "ProviderError",
    "RawPaperRecord",
    "RepositoryAnalysis",
    "RepositoryFileSummary",
    "RepositoryMetadata",
    "RepositoryPolicy",
    "RepositoryProvider",
    "RepositoryResolution",
    "RepositorySnapshotRepository",
    "ResearchRequestRepository",
    "RunManifest",
    "StaticRepositoryAnalyzer",
    "StructuredGenerationRequest",
    "StructuredGenerationResult",
    "StructuredLLM",
    "StructuredOutputValidationError",
    "SubmissionResult",
    "TrackerError",
    "TrackerRunRef",
    "UnitOfWork",
    "ValidationRunner",
    "ValidationStageSpec",
    "WorkspaceRef",
    "make_failure",
]
