"""Standard-library adapter contract used only by the controlled fixture probe."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_contract(path: Path = Path("sem_adaptation.json")) -> dict[str, Any]:
    """Load the deterministic config generated by SEM Research Agent."""
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("adaptation contract must be an object")
    return value


def build_one_batch(
    samples: list[list[float]],
    labels: list[str],
    groups: list[str],
    contract: dict[str, Any],
) -> dict[str, Any]:
    """Validate one synthetic batch against channels, labels, and group split."""
    channels = contract["input"]["channels"]
    mapping = contract["data"]["label_mapping"]
    if not samples or len(samples) != len(labels) or len(labels) != len(groups):
        raise ValueError("synthetic batch lengths must agree")
    if any(len(sample) != channels for sample in samples):
        raise ValueError("synthetic sample channel count does not match the contract")
    encoded = [mapping[label] for label in labels]
    if len(set(groups)) < 2:
        raise ValueError("group-split probe needs at least two synthetic groups")
    return {
        "batch_size": len(samples),
        "channels": channels,
        "encoded_labels": encoded,
        "group_count": len(set(groups)),
    }
